const wordList = {
  easy: [
    "cat",
    "dog",
    "sun",
    "moon",
    "star",
    "tree",
    "book",
    "pen",
    "desk",
    "chair",
    "bird",
    "fish",
    "cake",
    "milk",
    "rice",
    "soup",
    "hat",
    "shoe",
    "door",
    "wall",
    "ball",
    "game",
    "play",
    "run",
    "walk",
    "jump",
    "sing",
    "dance",
    "read",
    "write",
  ],
  medium: [
    "computer",
    "keyboard",
    "monitor",
    "internet",
    "website",
    "program",
    "network",
    "system",
    "database",
    "software",
    "hardware",
    "server",
    "browser",
    "display",
    "interface",
    "application",
    "development",
    "technology",
    "information",
    "security",
    "password",
    "username",
    "account",
    "profile",
    "message",
    "email",
    "contact",
    "address",
    "phone",
    "number",
  ],
  hard: [
    "algorithm",
    "architecture",
    "authentication",
    "authorization",
    "compilation",
    "configuration",
    "deployment",
    "encryption",
    "framework",
    "implementation",
    "infrastructure",
    "integration",
    "maintenance",
    "optimization",
    "performance",
    "protocol",
    "repository",
    "requirement",
    "specification",
    "synchronization",
    "virtualization",
    "visualization",
    "workflow",
    "workspace",
    "environment",
    "experience",
    "functionality",
    "interaction",
    "management",
    "organization",
  ],
};

export default wordList;
// edit 1412
// edit 6598
// edit 32297
// edit 3310
// edit 1824
// edit 9358
// edit 23281
// edit 3801
